### ISSUE TITLE
Challenge Sorting

### ISSUE THREAD

**Issue by n3tl0kr** [0xdevsachin/CTFD-odin-theme#1]
Hey!  Thank you for an awesome theme!  I noticed that the default sorting is point based and there doesn't seem to be a way to add a custom js handler like with the core-beta theme to sort by name, category or id.  Is this something you've experimented with or something easily addressed?

**Comment by 0xdevsachin** [comment]
You’re welcome! Currently, the default sorting is point-based, and adding a custom JavaScript handler for sorting by name, category, or ID might require modifications to the theme’s code. I recommend discussing this on the GitHub issues thread of [CTFD](https://github.com/CTFd/CTFd/blob/5bb3ffd73e6544691129ddf7b754b181ef9a8987/CONTRIBUTING.md) to gather insights from the community.
